import type { Request, Response } from "express";
import { PreInterviewBody } from "../types";
import { scrapeGithub } from "../scrapers/github";
import { Interview } from "../models/Interview";
import { Message } from "../models/Message";
import { calculateResult } from "../result";
import { generateInterviewerResponse } from "../services/groqService";
import { synthesizeSpeechWithDeepgram } from "../services/deepgramService";
import type { AuthRequest } from "../middleware/authMiddleware";

function extractGithubUsername(input: string): string {
  let clean = input.trim();
  clean = clean.replace(/\/+$/, "").replace(/\.git$/i, "");
  
  if (clean.includes("github.com/")) {
    const afterDomain = clean.split("github.com/")[1] || "";
    const parts = afterDomain.split("/").filter(Boolean);
    return parts[0] || clean;
  }
  
  const parts = clean.split("/").filter(Boolean);
  return parts[0] || clean;
}

/**
 * Creates pre-interview record and scrapes candidate GitHub info
 */
export async function createPreInterview(req: AuthRequest, res: Response): Promise<void> {
  try {
    const { success, data } = PreInterviewBody.safeParse(req.body);

    if (!success) {
      res.status(400).json({
        message: "Interview Title and GitHub URL are mandatory.",
      });
      return;
    }

    const mode = data.mode || (data.github ? "github" : data.jobDescription ? "jd" : "role");
    let githubData: any = {};

    if (mode === "github" && data.github) {
      const githubUsername = extractGithubUsername(data.github);
      githubData = await scrapeGithub(githubUsername);
    } else if (mode === "role") {
      githubData = { targetRole: data.role || "Software Engineer" };
    } else if (mode === "jd") {
      githubData = { jobDescription: data.jobDescription || "" };
    }

    const difficultyLabel = data.difficulty || "Medium";
    const dynamicTitle = data.title.trim();

    const interview = await Interview.create({
      userId: req.user?._id || undefined,
      title: dynamicTitle,
      mode,
      role: data.role || "",
      jobDescription: data.jobDescription || "",
      githubMetadata: githubData,
      difficulty: difficultyLabel,
      status: "Pre",
      score: 0,
      feedback: "",
    });

    res.json({ id: interview._id.toString() });
  } catch (error: any) {
    console.error("Pre-interview error:", error);
    res.status(500).json({
      message: error.message || "Failed to start pre-interview",
    });
  }
}

/**
 * Returns Deepgram key for frontend STT WebSocket
 */
export async function getDeepgramKey(req: Request, res: Response): Promise<void> {
  res.json({ key: process.env.DEEPGRAM_API_KEY || "" });
}

/**
 * Initiates the voice interview with an opening question generated by Groq + Deepgram TTS
 */
export async function initiateInterview(req: AuthRequest, res: Response): Promise<void> {
  try {
    const { interviewId } = req.params;
    const interview = await Interview.findById(interviewId);

    if (!interview) {
      res.status(404).json({ message: "Interview session not found" });
      return;
    }

    // Anti-cheating check: Enforce single device active per interview
    const token = req.headers.authorization ? req.headers.authorization.split(" ")[1] : "";
    if (interview.status === "InProgress" && interview.activeDeviceToken && interview.activeDeviceToken !== token) {
      res.status(403).json({
        message: "This interview session is already active on another device. Multi-device access is blocked for anti-cheating compliance.",
      });
      return;
    }

    if (!interview.activeDeviceToken || interview.status === "Pre") {
      interview.activeDeviceToken = token;
    }

    interview.status = "InProgress";
    await interview.save();

    // Check existing messages
    const existingMessages = await Message.find({ interviewId }).sort({ createdAt: 1 });
    if (existingMessages.length > 0) {
      const lastAiMessage = existingMessages.filter((m) => m.type === "Assistant").pop();
      const text = lastAiMessage ? lastAiMessage.message : "Welcome to your interview! Tell me about your background.";
      const tts = await synthesizeSpeechWithDeepgram(text);

      res.json({
        aiMessage: text,
        audioBase64: tts ? tts.audioBuffer.toString("base64") : null,
        contentType: tts?.contentType || "audio/mp3",
      });
      return;
    }

    // Generate initial welcome question via Groq
    const initialText = await generateInterviewerResponse(
      interview.githubMetadata, 
      [], 
      undefined, 
      interview.difficulty || "Medium"
    );

    // Save AI welcome question
    await Message.create({
      interviewId,
      type: "Assistant",
      message: initialText,
    });

    // Synthesize voice via Deepgram Aura TTS
    const tts = await synthesizeSpeechWithDeepgram(initialText);

    res.json({
      aiMessage: initialText,
      audioBase64: tts ? tts.audioBuffer.toString("base64") : null,
      contentType: tts?.contentType || "audio/mp3",
    });
  } catch (error: any) {
    console.error("Initiate interview error:", error);
    res.status(500).json({ message: error.message || "Failed to initiate session" });
  }
}

/**
 * Processes user candidate speech message via Groq LLM + Deepgram Aura TTS
 */
export async function processInterviewResponse(req: Request, res: Response): Promise<void> {
  try {
    const { interviewId } = req.params;
    const { message } = req.body;

    if (!interviewId || !message || !message.trim()) {
      res.status(400).json({ message: "Interview ID and user transcript message are required" });
      return;
    }

    const interview = await Interview.findById(interviewId);
    if (!interview) {
      res.status(404).json({ message: "Interview session not found" });
      return;
    }

    // Anti-cheating check: Block process response if request comes from different token
    const token = req.headers.authorization ? req.headers.authorization.split(" ")[1] : "";
    if (interview.activeDeviceToken && interview.activeDeviceToken !== token) {
      res.status(403).json({
        message: "Anti-cheating violation: This interview session is bound to another active device.",
      });
      return;
    }

    // 1. Save candidate message in MongoDB
    await Message.create({
      interviewId,
      type: "User",
      message: message.trim(),
    });

    // 2. Fetch all past messages for context
    const conversationHistory = await Message.find({ interviewId }).sort({ createdAt: 1 });
    const formattedTurns = conversationHistory.map((m) => ({
      type: m.type,
      message: m.message,
    }));

    // 3. Generate interviewer follow-up using Groq
    const aiText = await generateInterviewerResponse(
      interview.githubMetadata,
      formattedTurns,
      undefined,
      interview.difficulty || "Medium"
    );

    // 4. Save AI follow-up message in MongoDB
    await Message.create({
      interviewId,
      type: "Assistant",
      message: aiText,
    });

    // 5. Synthesize natural voice using Deepgram Aura TTS
    const tts = await synthesizeSpeechWithDeepgram(aiText);

    res.json({
      aiMessage: aiText,
      audioBase64: tts ? tts.audioBuffer.toString("base64") : null,
      contentType: tts?.contentType || "audio/mp3",
    });
  } catch (error: any) {
    console.error("Process interview response error:", error);
    res.status(500).json({ message: error.message || "Failed to process interview response" });
  }
}

/**
 * Saves candidate response (fallback endpoint)
 */
export async function saveUserResponse(req: Request, res: Response): Promise<void> {
  try {
    const { message } = req.body;
    const { interviewId } = req.params;

    if (!message || !interviewId) {
      res.status(400).json({ message: "Message and interviewId are required" });
      return;
    }

    await Message.create({
      interviewId,
      type: "User",
      message,
    });

    res.json({ message: "Message saved" });
  } catch (error: any) {
    console.error("Save user response error:", error);
    res.status(500).json({ message: error.message || "Failed to save response" });
  }
}

/**
 * Retrieves full interview result & evaluation (powered by Groq openai/gpt-oss-120b)
 */
export async function getResult(req: Request, res: Response): Promise<void> {
  try {
    const { interviewId } = req.params;

    const interview = await Interview.findById(interviewId);
    if (!interview) {
      res.status(404).json({ message: "Interview not found" });
      return;
    }

    const conversations = await Message.find({ interviewId }).sort({ createdAt: 1 });

    const transcript = conversations.map((c) => ({
      type: c.type,
      content: c.message,
      createdAt: c.createdAt,
    }));

    if (interview.status !== "Done" && conversations.length > 0) {
      try {
        const result = await calculateResult(
          conversations.map((c) => ({
            type: c.type,
            message: c.message,
            createdAt: c.createdAt,
          }))
        );

        interview.status = "Done";
        interview.score = result.overallScore || result.score || 0;
        interview.feedback = result.overallFeedback || result.feedback || "";
        interview.evaluationData = result;
        await interview.save();

        // Award +150 XP to candidate upon completing interview round
        if (interview.userId) {
          const User = (await import("../models/User")).User;
          const userObj = await User.findById(interview.userId);
          if (userObj) {
            userObj.xp = (userObj.xp || 0) + 150;
            // Update streak if active
            const now = new Date();
            const lastActive = userObj.lastActiveDate ? new Date(userObj.lastActiveDate) : null;
            if (!lastActive || (now.getTime() - lastActive.getTime()) > 24 * 60 * 60 * 1000) {
              userObj.streakDays = (userObj.streakDays || 1) + 1;
              userObj.lastActiveDate = now;
            }
            if (interview.score >= 9 && !userObj.badges?.includes("Ace Candidate")) {
              userObj.badges = [...(userObj.badges || []), "Ace Candidate"];
            }
            await userObj.save();
          }
        }
      } catch (calcError) {
        console.error("Groq AI Evaluation error:", calcError);
      }
    }

    res.json({
      score: interview.score,
      feedback: interview.feedback,
      evaluationData: interview.evaluationData,
      transcript,
      status: interview.status,
    });
  } catch (error: any) {
    console.error("Get result error:", error);
    res.status(500).json({ message: error.message || "Failed to retrieve result" });
  }
}

/**
 * Toggles bookmark status of an interview or question item
 */
export async function toggleBookmark(req: AuthRequest, res: Response): Promise<void> {
  try {
    if (!req.user) {
      res.status(401).json({ message: "Not authenticated" });
      return;
    }

    const { interviewId } = req.params;
    const interview = await Interview.findOne({ _id: interviewId, userId: req.user._id });

    if (!interview) {
      res.status(404).json({ message: "Interview record not found" });
      return;
    }

    interview.isBookmarked = !interview.isBookmarked;
    await interview.save();

    res.json({
      success: true,
      isBookmarked: interview.isBookmarked,
      message: interview.isBookmarked ? "Interview bookmarked" : "Bookmark removed",
    });
  } catch (error: any) {
    console.error("Toggle bookmark error:", error);
    res.status(500).json({ message: error.message || "Failed to update bookmark" });
  }
}

/**
 * Gets user's bookmarked interviews
 */
export async function getBookmarkedInterviews(req: AuthRequest, res: Response): Promise<void> {
  try {
    if (!req.user) {
      res.status(401).json({ message: "Not authenticated" });
      return;
    }

    const bookmarks = await Interview.find({ userId: req.user._id, isBookmarked: true })
      .sort({ updatedAt: -1 })
      .lean();

    res.json({
      success: true,
      bookmarks,
    });
  } catch (error: any) {
    console.error("Get bookmarked interviews error:", error);
    res.status(500).json({ message: error.message || "Failed to fetch bookmarks" });
  }
}

/**
 * Lists user's past interviews
 */
export async function getMyInterviews(req: AuthRequest, res: Response): Promise<void> {
  try {
    if (!req.user) {
      res.status(401).json({ message: "Not authenticated" });
      return;
    }

    const interviews = await Interview.find({ userId: req.user._id })
      .sort({ createdAt: -1 })
      .lean();

    res.json({
      success: true,
      interviews,
    });
  } catch (error: any) {
    console.error("Get my interviews error:", error);
    res.status(500).json({ message: error.message || "Failed to fetch user interviews" });
  }
}

/**
 * Corrects STT transcript errors for technical terms using Groq AI.
 * Only fixes misheared proper nouns / tech terms — never rewrites content.
 */
export async function correctTranscript(req: Request, res: Response): Promise<void> {
  try {
    const { text } = req.body as { text?: string };
    if (!text || !text.trim()) {
      res.status(400).json({ message: "text is required" });
      return;
    }

    const { getGroqClient } = await import("../services/groqService");
    const groq = getGroqClient();

    if (!groq) {
      // No Groq key — return original text unchanged
      res.json({ corrected: text });
      return;
    }

    const completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages: [
        {
          role: "system",
          content: `You are a technical transcript corrector for a developer interview. 
Your ONLY job is to fix speech recognition errors for technical terms, proper nouns, brand names, and programming concepts.

Rules (strictly follow):
- ONLY fix words that are clearly misheared technical/proper nouns (e.g. "mongo" → "MongoDB", "react" → "React", "node" → "Node.js", "express" → "Express.js", "java script" → "JavaScript", "type script" → "TypeScript", "post gres" → "PostgreSQL", "my sequel" → "MySQL", "git hub" → "GitHub", "docker" → "Docker", "kube" → "Kubernetes", "rest api" → "REST API", "jay son" → "JSON", "html" → "HTML", "css" → "CSS", "next js" → "Next.js").
- Do NOT rephrase, rewrite, add, or remove any content.
- Do NOT fix grammar or punctuation.
- Do NOT change words that are already correct.
- Return ONLY the corrected text, nothing else. No explanation, no quotes.`,
        },
        {
          role: "user",
          content: text.trim(),
        },
      ],
      temperature: 0.1,
      max_tokens: 500,
    });

    const corrected = completion.choices[0]?.message?.content?.trim() || text;
    res.json({ corrected });
  } catch (error: any) {
    console.error("Transcript correction error:", error);
    // On any error, return the original text so the interview is never blocked
    const { text } = req.body as { text?: string };
    res.json({ corrected: text || "" });
  }
}
