export const GLOBAL_COLLEGES: string[] = [
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) BHU Varanasi",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Palakkad",
  "Indian Institute of Technology (IIT) Dharwad",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Surathkal",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Allahabad (MNNIT)",
  "National Institute of Technology (NIT) Jaipur (MNIT)",
  "National Institute of Technology (NIT) Nagpur (VNIT)",
  "National Institute of Technology (NIT) Bhopal (MANIT)",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Jalandhar",
  "National Institute of Technology (NIT) Hamirpur",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Raipur",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Goa",
  "National Institute of Technology (NIT) Puducherry",
  "International Institute of Information Technology (IIIT) Hyderabad",
  "International Institute of Information Technology (IIIT) Bangalore",
  "Indraprastha Institute of Information Technology (IIIT) Delhi",
  "Indian Institute of Information Technology (IIIT) Allahabad",
  "Indian Institute of Information Technology (IIIT) Gwalior",
  "Indian Institute of Information Technology (IIIT) Lucknow",
  "Indian Institute of Information Technology (IIIT) Jabalpur",
  "Indian Institute of Information Technology (IIIT) Kancheepuram",
  "Indian Institute of Science (IISc) Bangalore",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "Birla Institute of Technology and Science (BITS) Goa",
  "Birla Institute of Technology and Science (BITS) Hyderabad",
  "Vellore Institute of Technology (VIT) Vellore",
  "Vellore Institute of Technology (VIT) Chennai",
  "Vellore Institute of Technology (VIT) AP",
  "Vellore Institute of Technology (VIT) Bhopal",
  "SRM Institute of Science and Technology (SRMIST) Kattankulathur",
  "SRM Institute of Science and Technology Ramapuram",
  "Manipal Institute of Technology (MIT) Manipal",
  "Manipal University Jaipur",
  "Thapar Institute of Engineering and Technology (TIET) Patiala",
  "Delhi Technological University (DTU) Delhi",
  "Netaji Subhas University of Technology (NSUT) Delhi",
  "College of Engineering Guindy (CEG) Anna University",
  "PSG College of Technology Coimbatore",
  "Coimbatore Institute of Technology (CIT)",
  "Thiagarajar College of Engineering Madurai",
  "SSN College of Engineering Chennai",
  "Savitribai Phule Pune University (SPPU)",
  "College of Engineering Pune (COEP) Technological University",
  "Vishwakarma Institute of Technology (VIT) Pune",
  "Pune Institute of Computer Technology (PICT) Pune",
  "Maharashtra Institute of Technology (MIT-WPU) Pune",
  "Veermata Jijabai Technological Institute (VJTI) Mumbai",
  "Sardar Patel Institute of Technology (SPIT) Mumbai",
  "K.J. Somaiya College of Engineering Mumbai",
  "University of Mumbai (MU)",
  "Jadavpur University Kolkata",
  "Heritage Institute of Technology Kolkata",
  "Institute of Engineering and Management (IEM) Kolkata",
  "Techno Main Salt Lake Kolkata",
  "Haldiya Institute of Technology West Bengal",
  "Osmania University Hyderabad",
  "Chaitanya Bharathi Institute of Technology (CBIT) Hyderabad",
  "Vasavi College of Engineering Hyderabad",
  "VNR Vignana Jyothi Institute of Engineering and Technology (VNRVJIET) Hyderabad",
  "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET) Hyderabad",
  "JNTU College of Engineering Hyderabad",
  "JNTU College of Engineering Kakinada",
  "Andhra University College of Engineering Visakhapatnam",
  "Gayatri Vidya Parishad College of Engineering Visakhapatnam",
  "KL University Guntur",
  "Vignan's Foundation for Science Technology and Research Guntur",
  "Bangalore University",
  "BMS College of Engineering Bangalore",
  "MS Ramaiah Institute of Technology (MSRIT) Bangalore",
  "RV College of Engineering (RVCE) Bangalore",
  "PES University Bangalore",
  "Dayananda Sagar College of Engineering Bangalore",
  "New Horizon College of Engineering Bangalore",
  "Sir M. Visvesvaraya Institute of Technology Bangalore",
  "Siddaganga Institute of Technology Tumkur",
  "JSS Science and Technology University Mysuru",
  "National Institute of Engineering (NIE) Mysuru",
  "Amrita Vishwa Vidyapeetham Coimbatore",
  "Amrita School of Engineering Bengaluru",
  "Amrita School of Engineering Amritapuri",
  "Sastra Deemed University Thanjavur",
  "Kalasalingam Academy of Research and Education",
  "Karunya Institute of Technology and Sciences Coimbatore",
  "Chandigarh University Mohali",
  "Lovely Professional University (LPU) Phagwara",
  "Chitkara University Punjab",
  "Panjab University Chandigarh",
  "Punjab Engineering College (PEC) Chandigarh",
  "Guru Nanak Dev Engineering College Ludhiana",
  "University of Delhi (DU)",
  "Jamia Millia Islamia Delhi",
  "Jawaharlal Nehru University (JNU) Delhi",
  "Guru Gobind Singh Indraprastha University (GGSIPU) Delhi",
  "Maharaja Agrasen Institute of Technology (MAIT) Delhi",
  "Maharaja Surajmal Institute of Technology (MSIT) Delhi",
  "Bharati Vidyapeeth's College of Engineering Delhi",
  "Amity University Noida",
  "Jaypee Institute of Information Technology (JIIT) Noida",
  "Galgotias University Greater Noida",
  "GL Bajaj Institute of Technology and Management Greater Noida",
  "KIET Group of Institutions Ghaziabad",
  "AKGEC Ghaziabad",
  "JSS Academy of Technical Education Noida",
  "Dr. A.P.J. Abdul Kalam Technical University (AKTU) Lucknow",
  "Harcourt Butler Technical University (HBTU) Kanpur",
  "Madan Mohan Malaviya University of Technology (MMMUT) Gorakhpur",
  "Institute of Engineering and Technology (IET) Lucknow",
  "University of Petroleum and Energy Studies (UPES) Dehradun",
  "Graphic Era University Dehradun",
  "DIT University Dehradun",
  "Malaviya National Institute of Technology (MNIT) Jaipur",
  "BITS Pilani Jaipur Campus",
  "Manipal University Jaipur",
  "LNM Institute of Information Technology (LNMIIT) Jaipur",
  "MBM Engineering College Jodhpur",
  "College of Technology and Engineering (CTAE) Udaipur",
  "Nirma University Ahmedabad",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT) Gandhinagar",
  "Pandit Deendayal Energy University (PDEU) Gandhinagar",
  "LD College of Engineering Ahmedabad",
  "Vishwakarma Government Engineering College (VGEC) Chandkheda",
  "MS University Vadodara",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT) Surat",
  "Visvesvaraya National Institute of Technology (VNIT) Nagpur",
  "G.H. Raisoni College of Engineering Nagpur",
  "Shri Ramdeobaba College of Engineering and Management (RCOEM) Nagpur",
  "Government College of Engineering Amravati",
  "Government College of Engineering Aurangabad",
  "Walchand College of Engineering Sangli",
  "Sardar Patel College of Engineering (SPCE) Mumbai",
  "K.J. Somaiya Institute of Engineering and Information Technology Mumbai",
  "St. Xavier's Institute of Engineering Mumbai",
  "Fr. Conceicao Rodrigues College of Engineering Mumbai",
  "Thadomal Shahani Engineering College Mumbai",
  "Vidyalankar Institute of Technology Mumbai",
  "Don Bosco Institute of Technology Mumbai",
  "Government Engineering College Thrissur",
  "College of Engineering Trivandrum (CET)",
  "Model Engineering College (MEC) Kochi",
  "TKM College of Engineering Kollam",
  "Mar Athanasius College of Engineering Kothamangalam",
  "Muthoot Institute of Technology and Science Kochi",
  "Rajagiri School of Engineering and Technology Kochi",
  "Federal Institute of Science and Technology (FISAT) Angamaly",
  "Scms School of Engineering and Technology Kochi",
  "Government Engineering College Barton Hill Thiruvananthapuram",
  "National Institute of Technology (NIT) Meghalaya",
  "National Institute of Technology (NIT) Nagaland",
  "National Institute of Technology (NIT) Mizoram",
  "National Institute of Technology (NIT) Manipur",
  "A M Reddy Memorial College of Pharmacy, Petlurivaripalem, Narasaropet",
  "Andhra Loyola College, Vijayawada",
  "Bapatla Engineering College, Bapatla",
  "Chalapathi Institute of Engineering & Technology, Guntur",
  "Chalapathi Institute of Pharmaceutical Sciences, Guntur",
  "Chebrolu Hanumaiah Institute of Pharmaceutical Sciences, Guntur",
  "Govt. College for Women, Sambasiva Pet, Guntur",
  "J.M.J. College of Women, Tenali",
  "Jagarlamudi Kuppuswamy Choudary College, Guntur",
  "Kakaraparti Bhavanarayana College, Vijayawada",
  "Krishnaveni Degree College, Narasaraopet",
  "Medarametla Anjamma Mastanrao College of Pharmacy, Narasaraopet",
  "Montessori Mahila Kalasala, Vijayawada",
  "Nirmala College of Pharmacy, Mangalagiri, Guntur",
  "R.V.R. & J.C. College of Engineering, Guntur",
  "Sri A.B.R. Government Degree College, Repalle",
  "Sri Velagapudi Ramakrishna Memorial College, Nagaram",
  "St. Joseph’s College of Education for Women, Guntur",
  "T.R.R. Government Degree College, Kandukur",
  "V.S.R.& N.V.R. College, Tenali",
  "Aditya Degree College for Women, Kakinada",
  "Aditya Degree College, Kakinada",
  "A.S.D. Government Degree College for Women, Kakinada",
  "B. V. Raju College, Bhimavaram",
  "Chintelepati Satyavati Devi St. Theresa’s College for Women, Eluru",
  "Dantuluri Narayanan Raju College, Bhimavaram",
  "Govt. Degree College, Rajahmundry",
  "Government Degree College, Tuni",
  "Ideal College of Arts & Science, Kakinada",
  "K.G.R.L. College, Bhimavaram",
  "P.R. Govt. Degree College (Men), Kakinada",
  "Sir C R Reddy College, Eluru",
  "S.K.S.D. Mahila Kalasala, Tanuku",
  "Sri A.S.N.M. Govt. College, Palakol",
  "S.V.K.P. & Dr. K.S. Raju Arts & Science College, Penugonda",
  "Sri Yerramilli Narayana Murthy College, Narsapur",
  "V.S.M. College, Ramachandrapuram",
  "D.S. Government Degree College for Women, Ongole",
  "Andhra University College of Engineering, Visakhapatnam",
  "Anil Neerukonda Institute of Technology & Sciences, Visakhapatnam",
  "Dr Lankapalli Bullayya College of Engineering, Visakhapatnam",
  "Dr. V.S. Krishna Government Degree College, Visakhapatnam",
  "Gayatri College of Science & Management, Srikakulam",
  "Gayatri Vidya Parishad College & P.G Courses, Visakhapatnam",
  "Gayatri Vidya Parishad College of Engineering for Women, Visakhapatnam",
  "GIET School of Pharmacy, Rajahmundry",
  "Maharajah’s College, Vizianagaram",
  "Sagi Rama Krishnam Raju Engineering College, Bhimavaram",
  "S.G.A. Govt. Degree College, Yellamanchili",
  "Shri Durgaprasad Saraf College of Arts & Applied Sciences, Vizianagaram",
  "Shri Vishnu College of Pharmacy, Bhimavaram",
  "Sir C.R. Reddy College of Pharmaceutical Sciences, Eluru",
  "Spaces Degree College, Payakaraopeta",
  "St. Ann's College for Women, Visakhapatnam",
  "St. Joseph’s College for Women, Visakhapatnam",
  "Visakha Govt Degree College for Women, Visakhapatnam",
  "Government College for Women, Srikakulam",
  "ABR College of Engineering and Technology, Kanigiri",
  "Aditya College of Engineering, Surampalem",
  "Aditya College of Engineering & Technology, Surampalem",
  "Aditya College of Pharmacy, Surampalem",
  "Aditya Engineering College, Surampalem",
  "Aditya Institute of Technology and Management, Tekkali",
  "Aditya Pharmacy College, Surampalem",
  "Amrita Sai Institute of Science and Technology, Paritala",
  "A. M. Reddy Memorial College of Engineering and Technology, Narasaraopet",
  "Andhra Loyola Institute of Engineering and Technology, Vijayawada",
  "Bhimavaram Institute of Engineering & Technology, Bhimavaram",
  "Bonam Venkata Chalamayya Engineering College, Odalarevu",
  "Bonam Venkata Chalamayya Institute of Technology & Science, East Godavari",
  "BVC College of Engineering, Rajahmundry",
  "Chalapathi Institute of Technology, Guntur",
  "Chebrolu Engineering College, Guntur",
  "Chirala Engineering College, Chirala",
  "Devineni Venkata Ramana & Dr. Hima Sekhar MIC College of Technology, Kanchikacherla",
  "Dhanekula Institute of Engineering and Technology, Vijayawada",
  "DNR College of Engineering and Technology, Bhimavaram",
  "Dr. Samuel George Institute of Engineering and Technology, Markapur",
  "Eswar College of Engineering, Narasaraopet",
  "GIET Engineering College, Rajahmundry",
  "G.M.R. Institute of Technology, Rajam",
  "Gayatri Vidya Parishad College of Engineering, Visakhapatnam",
  "Godavari Institute of Engineering & Technology, Rajahmundry",
  "Seshadri Rao Gudlavalleru Engineering College, Gudlavalleru",
  "International School of Technology and Sciences, Rajahmundry",
  "JNT University College of Engineering, Kakinada",
  "JNTUK University College of Engineering, Vizianagaram",
  "Lakireddy Bali Reddy College of Engineering, Mylavaram",
  "Kakinada Institute of Technology and Science, Divili",
  "Kallam Haranadhareddy Institute of Technology, Guntur",
  "KITS Akshar Institute of Technology, Guntur",
  "KKR & KSR Institute of Technology & Science, Guntur",
  "Lendi Institute of Engineering and Technology, Vizianagaram",
  "Lingayas Institute of Management and Technology, Vijayawada",
  "Maharaj Vijayaram Gajapathi Raj College of Engineering, Vizianagaram",
  "Malineni Lakshmaiah Women’s Engineering College, Guntur",
  "Mandava Institute of Engineering and Technology, Jaggaiahpet",
  "MVR College of Engineering & Technology, Vijayawada",
  "Nadimpalli Satyanarayana Raju Institute of Technology, Visakhapatnam",
  "Narasaraopeta Engineering College, Narasaraopet",
  "Narasaraopeta Institute of Pharmaceutical Sciences, Narasaraopet",
  "Nimra College of Pharmacy, Ibrahimpatnam",
  "Nimra College of Engineering and Technology, Ibrahimpatnam",
  "Newton’s Institute of Engineering, Macherla",
  "NRI College of Pharmacy, Agiripalli",
  "NRI Institute of Technology, Agiripalli",
  "PACE Institute of Technology & Sciences, Ongole",
  "Potti Sriramulu Chalavadi Mallikarjuna Rao College of Engineering and Technology, Vijayawada",
  "Pragati Engineering College, Surampalem",
  "Prakasam Engineering College, Kandukur",
  "Prasad V. Potluri Siddhartha Institute of Technology, Vijayawada",
  "Priyadarshini Institute of Technology and Management, Guntur",
  "Priyadarshni Institute of Technology and Science, Duggirala",
  "Pydah College of Engineering, Kakinada",
  "QIS College of Engineering & Technology, Ongole",
  "Ramachandra College of Engineering, Eluru",
  "Raghu Institute of Technology, Visakhapatnam",
  "Rajamahendri Institute of Engineering & Technology, Rajahmundry",
  "Rise Krishna Sai Gandhi Group of Institutions, Ongole",
  "R K College of Engineering, Vijayawada",
  "Sasi Institute of Technology & Engineering, Tadepalligudem",
  "Shri Vishnu Engineering College for Women, Bhimavaram",
  "Sree Vahini Institute of Science and Technology, Tiruvuru",
  "Sir C R Reddy College of Engineering, Eluru",
  "Sri Mittapalli College of Engineering, Guntur",
  "Sri Vasavi Institute of Engineering & Technology, Pedana",
  "Srinivasa Institute of Engineering and Technology, Amalapuram",
  "Sri Vasavi Engineering College, Tadepalligudem",
  "SRK Institute of Technology, Vijayawada",
  "St. Ann’s College of Engineering & Technology, Chirala",
  "Swarnandhra College of Engineering & Technology, Narsapur",
  "Tirumala Engineering College, Guntur",
  "Universal College of Engineering and Technology, Guntur",
  "Usha Rama College of Engineering and Technology, Telaprolu",
  "V.S.M. College of Engineering, Ramachandrapuram",
  "Vasireddy Venkatadri Institute of Technology, Guntur",
  "Velagapudi Ramakrishna Siddhartha Engineering College, Vijayawada",
  "Vignan’s Institute of Information Technology (VIIT), Visakhapatnam",
  "Vignan's Lara Institute of Technology & Science, Guntur",
  "Vignan Pharmacy College, Guntur",
  "Vignan's Nirula Institute of Technology and Science for Women, Guntur",
  "Vijaya Institute of Pharmaceutical Sciences for Women, Vijayawada",
  "Vikas College of Engineering and Technology, Vijayawada",
  "Vikas Group of Institutions, Vijayawada",
  "Vishnu Institute of Technology, Bhimavaram",
  "V.R.K, V.N.B & A.G.K. College of Engineering, Gudivada",
  "West Godavari Institute of Science and Engineering, Nallajerla",
  "Avanthi Institute of Engineering and Technology, Bhogapuram",
  "Avanthi Institute of Engineering and Technology, Narsipatnam",
  "Baba Institute of Technology and Sciences, Visakhapatnam",
  "Dadi Institute of Engineering & Technology, Anakapalle",
  "Miracle Educational Society Group of Institutions, Vizianagaram",
  "Raghu Engineering College, Visakhapatnam",
  "Sri Sivani College of Engineering, Srikakulam",
  "Vignan Institute of Pharmaceutical Technology, Visakhapatnam",
  "Vignan’s Institute of Engineering for Women, Visakhapatnam",
  "Visakha Institute of Engineering & Technology, Visakhapatnam",
  "Aditya College of Engineering, Madanapalle",
  "Annamacharya College of Pharmacy, Rajampet",
  "Annamacharya Institute of Technology and Sciences, Rajampet",
  "Annamacharya Institute of Technology and Sciences, Tirupati",
  "Annamacharya Institute of Technology and Sciences, Kadapa",
  "Anantha Lakshmi Institute of Technology and Sciences, Anantapur",
  "Ashoka Women's Engineering College, Kurnool",
  "Audisankara College of Engineering and Technology, Gudur",
  "Audisankara Institute of Technology, Gudur",
  "Chadalawada Ramanamma Engineering College, Tirupati",
  "Chaitanya Bharathi Institute of Technology, Proddatur",
  "Dr. K. V. Subba Reddy Institute of Pharmacy, Kurnool",
  "Dr. K.V. Subba Reddy Institute of Technology, Kurnool",
  "G. Pullaiah College of Engineering and Technology, Kurnool",
  "G. Pulla Reddy Engineering College, Kurnool",
  "Geethanjali Institute of Science and Technology, Nellore",
  "Gates Institute of Technology, Gooty",
  "Gouthami Institute of Technology and Management for Women, Proddatur",
  "JNTU Anantapur College of Engineering, Anantapur",
  "K.S.R.M. College of Engineering, Kadapa",
  "Kuppam Engineering College, Kuppam",
  "Madanapalle Institute of Technology & Science, Madanapalle",
  "Mahathi College of Pharmacy, Madanapalle",
  "Mother Theresa Institute of Engineering and Technology, Palamaner",
  "Narayana Engineering College, Nellore",
  "Narayana Engineering College, Gudur",
  "NBKR Institute of Science and Technology, Vidhyanagar",
  "Nirmala College of Pharmacy, Kadapa",
  "PVKK Institute of Technology, Anantapuramu",
  "Parvathareddy Babul Reddy Visvodaya Institute of Technology & Science, Kavali",
  "P. Rami Reddy Memorial College of Pharmacy, Kadapa",
  "Raghavendra Institute of Pharmaceutical Education and Research (RIPER), Anantapur",
  "Rajeev Gandhi Memorial College of Engineering & Technology, Nandyal",
  "RamiReddy Subbarami Reddy Engineering College, Bogole",
  "Ravindra College of Engineering for Women, Kurnool",
  "Rise Krishna Sai Prakasam Group of Institutions, Ongole",
  "Sai Rajeswari Institute of Technology, Proddatur",
  "Sanskrithi School of Business, Puttaparthi",
  "Santhiram College of Pharmacy, Nandyal",
  "Santhiram Engineering College, Nandyal",
  "Seven Hills College of Pharmacy, Tirupati",
  "Siddartha Educational Academy Group of Institutions, Tirupati",
  "Siddharth Institute of Engineering & Technology, Puttur",
  "Siddartha Institute of Science and Technology, Puttur",
  "Sir C V Raman Institute of Technology and Sciences, Tadipatri",
  "Sree Rama Engineering College, Tirupati",
  "Sri Sai Institute of Technology and Science, Rayachoty",
  "Sree Vidyanikethan Engineering College, Tirupati",
  "Sreenivasa Institute of Technology and Management Studies (SITAMS), Chittoor",
  "Srinivasa Institute of Technology and Science, Kadapa",
  "Srinivasa Ramanujan Institute of Technology, Anantapuramu",
  "Sri Padmavathi School of Pharmacy, Tirupati",
  "Sri Venkateswara College of Engineering & Technology, Chittoor",
  "Sri Venkateswara College of Engineering, Tirupati",
  "Sree Venkateswara College of Engineering, Nellore",
  "Sri Venkateswara Institute of Technology, Anantapuramu",
  "Sri Venkatesaperumal College of Engineering & Technology, Puttur",
  "Sri Venkateswara College of Pharmacy, Chittoor",
  "St. Johns College of Engineering & Technology, Yemmiganur",
  "St. John's College of Pharmaceutical Sciences, Yemmiganur",
  "SVR Engineering College, Nandyal",
  "Tadipatri Engineering College, Tadipatri",
  "Vaagdevi Institute of Technology & Science, Proddatur",
  "Vemu Institute of Technology, Tirupati",
  "Viswam Engineering College, Madanapalle",
  "Adusumilli Gopalakrishnaiah & Sugarcane Growers Siddhartha Degree College, Vuyyuru",
  "Akkineni Nageswara Rao College, Gudivada",
  "KVSR Siddhartha College of Pharmaceutical Sciences, Vijayawada",
  "Maris Stella College, Vijayawada",
  "P.B. Siddhartha College of Arts & Science, Vijayawada",
  "Sri Durga Malleswara Siddhartha Mahila Kalasala, Vijayawada",
  "SRR & CVR Govt. Degree College, Vijayawada",
  "K.V.R. Govt. College for Women, Kurnool",
  "Osmania College, Kurnool",
  "Silver Jubilee Government Degree College, Kurnool",
  "Sri Ramakrishna Degree College, Nandyal",
  "Government College (Autonomous) (Men), Anantapur",
  "K.S.N. Government Degree College for Women, Ananthapuramu",
  "SKP Govt Degree College, Guntakal",
  "Sri Sai Baba National Degree College, Anantapur",
  "S.S.G.S. Degree College, Guntakal",
  "Government Degree College, Nagari",
  "P.V.K.N. Govt. College, Chittoor",
  "Shri Gnanambica Degree College, Madanapalle",
  "Smt. N.P.S Govt. College for Women, Chittoor",
  "Sri Padmavathi Women’s Degree & PG College, Tirupati",
  "Sri Venkateswara University College of Engineering, Tirupati",
  "S.G.S. Arts College, Tirupati",
  "S. V. Arts College, Tirupati",
  "Vijayam Science and Arts Degree College, Chittoor",
  "D. K. College for Women, Nellore",
  "Krishna Chaitanya Degree College, Nellore",
  "Krishna Chaitanya Institute of Science and Technology, Nellore",
  "Sri V. S. Sivalingam Chettiar Government Degree College, Sullurpet",
  "CSSR & SRRM Degree & PG College, Kamalapuram",
  "Government College for Men, Kadapa",
  "SKR & SKR Govt. College for Women, Kadapa",
  "Sri Hari Degree College, Kadapa",
  "Sri Rachapudy Nagabhushanam Degree & PG College, Badvel",
  "Sri Vivekananda Degree College for Women, Kadapa",
  "Sri Venkateswara College of Arts and Computer Sciences, Proddatur",
  "Saint Claret College, Ziro",
  "Bir Lachit Borphukan College, Sivasagar",
  "Debraj Roy College, Golaghat",
  "Dibrugarh Hanumanbax Surajmall Kanoi College, Dibrugarh",
  "Digboi College, Digboi",
  "Dhakuakhana College, Lakhimpur",
  "Golaghat Commerce College, Golaghat",
  "Hemo Prova Borbora Girls' College, Golaghat",
  "Jagannath Barooah College, Jorhat",
  "Furkating College, Golaghat",
  "North Lakhimpur College, Lakhimpur",
  "Sibsagar College, Sivasagar",
  "Tinsukia Commerce College, Tinsukia",
  "Arya Vidyapeeth College, Guwahati",
  "B Borooah College, Guwahati",
  "B N College, Dhubri",
  "Chaiduar College, Gohpur",
  "Darrang College, Tezpur",
  "Dimoria College, Khetri",
  "Jagiroad College, Morigaon",
  "Morigaon College, Morigaon",
  "Nowgong College, Nagaon",
  "Rangapara College, Sonitpur",
  "Sonapur College, Sonapur",
  "Suren Das College, Hajo",
  "Patna Women’s College, Patna",
  "St. Xavier’s College of Education, Patna",
  "St. Xavier's College of Management & Technology, Patna",
  "Lalit Narayan Mishra College of Business Management, Muzaffarpur",
  "Bhilai Institute of Technology, Durg",
  "Rungta College of Engineering and Technology, Bhilai",
  "Shri Shankaracharya Technical Campus, Bhilai",
  "Govt. E. Raghavendra Rao PG Science College, Bilaspur",
  "Govt. Dudhdhari Bajrang Girls' PG College, Raipur",
  "Govt. Digvijay Autonomous College, Rajnandgaon",
  "Govt. V.Y.T. (PG) Autonomous College, Durg",
  "Rajeev Gandhi Govt. Postgraduate College, Ambikapur",
  "Jagannath International Management School (J.I.M.S.), Delhi",
  "Lingaya's Lalita Devi Institute of Management and Sciences, Delhi",
  "Maharaja Agrasen Institute of Management Studies, Delhi",
  "Government College of Commerce and Economics, Margao",
  "Parvatibai Chowgule College of Arts and Sciences, Margao",
  "S. S. Dempo College of Commerce and Economics, Panjim",
  "M G Science Institute, Ahmedabad",
  "St. Xavier’s College, Ahmedabad",
  "Birla Vishvakarma Mahavidyalaya, Vallabh Vidyanagar",
  "L. M. College of Pharmacy, Ahmedabad",
  "Shree Dhanvantary Pharmacy College, Kim",
  "CP Patel and F H Shah Commerce College, Anand",
  "Vitthalbhai Patel & Rajratna P T Patel Science College, Vallabh Vidyanagar",
  "P.T. Sarvajanik College of Science, Surat",
  "Panipat Institute of Engineering and Technology, Panipat",
  "BRCM College of Engineering and Technology, Bhiwani",
  "DPG Degree College, Gurugram",
  "Ganga Institute of Technology and Management, Jhajjar",
  "Dogra Degree College, Jammu",
  "Govt. College for Women Parade, Jammu",
  "Govt. College of Engineering and Technology, Jammu",
  "MIER College of Education, Jammu",
  "Model Institute of Engineering & Technology, Jammu",
  "Govt. Degree College, Baramulla",
  "The Islamia College of Science & Commerce, Srinagar",
  "Marwari College, Ranchi",
  "Ranchi Women’s College, Ranchi",
  "St. Xavier’s College, Ranchi",
  "Acharya Bangalore B School, Bangalore",
  "IFIM College, Electronic City, Bangalore",
  "Jyoti Nivas College, Bangalore",
  "Kristu Jayanti College, Bangalore",
  "Krupanidhi College of Management, Bangalore",
  "Maharani Lakshmi Ammanni College for Women, Bangalore",
  "Mount Carmel College, Bangalore",
  "NMKRV College for Women, Bangalore",
  "Padmashree Institute of Management and Sciences, Bangalore",
  "RNS First Grade College, Bangalore",
  "St. Claret College, Bangalore",
  "St. Francis De Sales College, Bangalore",
  "St. Joseph's College of Commerce, Bangalore",
  "St. Joseph's College, Bangalore",
  "Surana College, Bangalore",
  "The National College, Jayanagar, Bangalore",
  "The National Degree College, Basavangudi, Bangalore",
  "T. John College, Bangalore",
  "B.M.S. College for Women, Bengaluru",
  "International Institute of Business Studies, Bangalore",
  "Jain College, V.V. Puram, Bengaluru",
  "MS Ramaiah College of Arts, Science and Commerce, Bengaluru",
  "Presidency College, Bengaluru",
  "RV Institute of Management, Bengaluru",
  "K.L.E. Society’s P.C. Jabin Science College, Hubli",
  "Government College, Kalaburagi",
  "B.M.S. College of Law, Bengaluru",
  "JSS Law College, Mysore",
  "A J Institute of Management, Mangalore",
  "Alva’s College, Moodubidire",
  "Canara College, Mangaluru",
  "Mahatma Gandhi Memorial College, Udupi",
  "Poornaprajna College, Udupi",
  "School of Social Work Roshni Nilaya, Mangalore",
  "Sri Dharmasthala Manjunatheshwara College, Ujire",
  "St. Agnes College, Mangalore",
  "St. Aloysius College, Mangalore",
  "St Philomena College, Puttur",
  "Vivekananda College, Puttur",
  "Bharathi College, Mandya",
  "JSS College for Women, Saraswathipuram, Mysore",
  "JSS College of Arts, Commerce and Science, Mysore",
  "Maharani’s Science College for Women, Mysuru",
  "SBRR Mahajana First Grade College, Mysuru",
  "St. Philomena’s College, Mysore",
  "Yuvaraja’s College, Mysore",
  "K.L.E. Society’s Lingaraj College, Belgaum",
  "KLS Institute of Management Education and Research, Belagavi",
  "Raja Lakhamagouda Science Institute, Belgaum",
  "Govindram Seksaria Science College, Belgaum",
  "Acharya & BM Reddy College of Pharmacy, Bengaluru",
  "Krupanidhi College of Pharmacy, Bengaluru",
  "Alva's Institute of Engineering and Technology, Moodbidri",
  "AMC Engineering College, Bengaluru",
  "Atria Institute of Technology, Bengaluru",
  "Ballari Institute of Technology & Management, Ballari",
  "Bapuji Institute of Engineering and Technology, Davangere",
  "B.M.S. College of Engineering, Bangalore",
  "BMS Institute of Technology and Management, Bangalore",
  "BNM Institute of Technology, Bangalore",
  "Bangalore Institute of Technology, Bangalore",
  "Basaveshwar Engineering College, Bagalkot",
  "Cambridge Institute of Technology, Bengaluru",
  "Canara Engineering College, Bantwala",
  "Dayananda Sagar College of Engineering, Bangalore",
  "Dayananda Sagar Academy of Technology & Management, Bangalore",
  "Don Bosco Institute of Technology, Bangalore",
  "Dr. Ambedkar Institute of Technology, Bangalore",
  "East Point College of Engineering and Technology, Bengaluru",
  "East West Institute of Technology, Bangalore",
  "Global Academy of Technology, Bengaluru",
  "KLS Gogte Institute of Technology, Belagavi",
  "M.S. Ramaiah Institute of Technology, Bangalore",
  "Maharaja Institute of Technology, Mysore",
  "Malnad College of Engineering, Hassan",
  "Nagarjuna College of Engineering and Technology, Bengaluru",
  "New Horizon College of Engineering, Bangalore",
  "Nitte Meenakshi Institute of Technology, Bangalore",
  "NMAM Institute of Technology, Nitte",
  "M.V.J. College of Engineering, Bangalore",
  "Mangalore Institute of Technology & Engineering, Moodabidri",
  "P.E.S. College of Engineering, Mandya",
  "Poojya Doddappa Appa College of Engineering, Kalaburagi",
  "Rajarajeswari College of Engineering, Bengaluru",
  "RNS Institute of Technology, Bengaluru",
  "R.V. College of Engineering, Bangalore",
  "Sahyadri College of Engineering & Management, Mangaluru",
  "S.D.M. College of Engineering and Technology, Dharwad",
  "Sir M. Visvesvaraya Institute of Technology, Bengaluru",
  "SJB Institute of Technology, Bangalore",
  "SJC Institute of Technology, Chickballapur",
  "Siddaganga Institute of Technology, Tumkur",
  "St. Joseph Engineering College, Mangaluru",
  "The National Institute of Engineering, Mysore",
  "Vidyavardhaka College of Engineering, Mysuru",
  "Amal Jyothi Engineering College, Kottayam",
  "Jawaharlal College of Engineering and Technology, Palakkad",
  "Jyothi Engineering College, Thrissur",
  "Mar Athanasius College of Engineering, Kothamangalam",
  "Mar Baselios College of Engineering and Technology, Thiruvananthapuram",
  "Nehru College of Engineering and Research Centre, Thrissur",
  "Rajagiri School of Engineering & Technology, Kochi",
  "Sahrdaya College of Engineering and Technology, Thrissur",
  "Saintgits College of Engineering, Kottayam",
  "Sree Buddha College of Engineering, Alappuzha",
  "St. Joseph's College of Engineering and Technology, Palai",
  "TKM College of Engineering, Kollam",
  "Vimal Jyothi Engineering College, Kannur",
  "Viswajyothi College of Engineering and Technology, Muvattupuzha",
  "Assumption College, Changanassery",
  "CMS College, Kottayam",
  "Maharaja’s College, Ernakulam",
  "Mar Athanasious College, Kothamangalam",
  "Marian College, Kuttikkanam",
  "Nirmala College, Muvattupuzha",
  "Rajagiri College of Social Sciences, Kalamassery",
  "Sacred Heart College, Thevara",
  "St. Albert’s College, Ernakulam",
  "St. Berchmans College, Changanassery",
  "St. Teresa’s College, Ernakulam",
  "St. Thomas College, Palai",
  "Union Christian College, Aluva",
  "Christ College, Irinjalakuda",
  "Farook College, Calicut",
  "M.E.S. Mampad College, Malappuram",
  "St. Joseph’s College, Devagiri",
  "St. Joseph’s College, Irinjalakuda",
  "St. Thomas College, Thrissur",
  "Vimala College, Thrissur",
  "Fatima Mata National College, Kollam",
  "Mar Ivanios College, Thiruvananthapuram",
  "Bhopal School of Social Sciences, Bhopal",
  "Institute for Excellence in Higher Education (IEHE), Bhopal",
  "Govt. Holkar (Model Autonomous) Science College, Indore",
  "Indore Institute of Law, Indore",
  "IPS Academy, Institute of Business Management and Research, Indore",
  "Prestige Institute of Management & Research, Indore",
  "Govt. Kamala Raja Girls PG Autonomous College, Gwalior",
  "M.L.B. Arts and Commerce College, Gwalior",
  "Prestige Institute of Management, Gwalior",
  "IPS Academy Institute of Engineering and Sciences, Indore",
  "Samrat Ashok Technological Institute, Vidisha",
  "Shri G.S. Institute of Technology & Science, Indore",
  "Govt. Mahakoshal Arts & Commerce Autonomous College, Jabalpur",
  "Mata Gujri Mahila Mahavidyalaya, Jabalpur",
  "St. Aloysius College, Jabalpur",
  "Govt. College of Engineering, Chhatrapati Sambhajinagar",
  "Maharashtra Institute of Technology, Aurangabad",
  "Deogiri College, Aurangabad",
  "Bhusawal Arts, Science and P.O. Nahata Commerce College, Bhusawal",
  "Government College of Engineering, Jalgaon",
  "G.H. Raisoni Institute of Business Management, Jalgaon",
  "Moolji Jaitha College, Jalgaon",
  "R.C. Patel Institute of Pharmaceutical Education and Research, Shirpur",
  "Amrutvahini College of Engineering, Sangamner",
  "Army Institute of Technology (AIT), Pune",
  "AISSMS College of Engineering, Pune",
  "AISSMS Institute of Information Technology, Pune",
  "Vishwakarma Institute of Technology (VIT), Pune",
  "Vishwakarma Institute of Information Technology (VIIT), Pune",
  "B.M. College of Commerce, Pune",
  "D.Y. Patil College of Engineering, Akurdi",
  "Fergusson College, Pune",
  "G.H. Raisoni College of Engineering & Management, Pune",
  "Indira Institute of Management, Pune",
  "JSPM’s Rajarishi Shahu College of Engineering, Tathwade",
  "K.K. Wagh Institute of Engineering Education and Research, Nashik",
  "Cummins College of Engineering for Women, Pune",
  "Abasaheb Garware College, Pune",
  "Garware College of Commerce, Pune",
  "MIT Academy of Engineering, Alandi",
  "Modern College of Arts, Science and Commerce, Shivajinagar",
  "Modern College of Arts, Science and Commerce, Ganeshkhind",
  "Modern College of Engineering, Pune",
  "PVG's College of Engineering and Technology, Pune",
  "Sanjivani College of Engineering, Kopargaon",
  "Indira College of Commerce and Science, Pune",
  "Pune Institute of Computer Technology (PICT), Pune",
  "Sir Parashurambhau College, Pune",
  "St. Mira’s College for Girls, Pune",
  "Symbiosis College of Arts & Commerce, Pune",
  "Pimpri Chinchwad College of Engineering (PCCoE), Pune",
  "Zeal College of Engineering and Research, Pune",
  "Datta Meghe Institute of Management Studies, Nagpur",
  "G.H. Raisoni College of Engineering, Nagpur",
  "G.S. College of Commerce & Economics, Nagpur",
  "Institute of Science, Nagpur",
  "Bajaj College of Science, Wardha",
  "Jhulelal Institute of Technology, Nagpur",
  "KDK College of Engineering, Nagpur",
  "Priyadarshini College of Engineering, Nagpur",
  "S. B. Jain Institute of Technology, Management & Research, Nagpur",
  "Shri Ramdeobaba College of Engineering & Management, Nagpur",
  "St. Vincent Pallotti College of Engineering & Technology, Nagpur",
  "Yeshwantrao Chavan College of Engineering (YCCE), Nagpur",
  "S.V.T. College of Home Science, Mumbai",
  "Government College of Engineering, Amravati",
  "Prof. Ram Meghe Institute of Technology & Research, Badnera",
  "P. R. Pote Patil College of Engineering and Management, Amravati",
  "Sipna College of Engineering and Technology, Amravati",
  "Annasaheb Dange College of Engineering and Technology, Ashta",
  "Chhatrapati Shahu Institute of Business Education & Research (CSIBER), Kolhapur",
  "DKTE Society’s Textile and Engineering Institute, Ichalkaranji",
  "D.Y. Patil College of Engineering and Technology, Kolhapur",
  "Government College of Engineering, Karad",
  "Kolhapur Institute of Technology’s College of Engineering, Kolhapur",
  "Rajarambapu Institute of Technology, Islampur",
  "Sadguru Gadge Maharaj College, Karad",
  "Tatyasaheb Kore Institute of Engineering and Technology, Waranagar",
  "Vivekanand College, Kolhapur",
  "Walchand College of Engineering, Sangli",
  "Yashvantrao Chavan Institute of Science, Satara",
  "Karmaveer Bhaurao Patil Mahavidyalaya, Pandharpur",
  "Sangameshwar College, Solapur",
  "SVERI's College of Engineering, Pandharpur",
  "Walchand Institute of Technology, Solapur",
  "Rajarshi Shahu Mahavidyalaya, Latur",
  "Shri Guru Gobind Singhji Institute of Engineering and Technology, Nanded",
  "Fr. C. Rodrigues Institute of Technology, Vashi",
  "B.K. Birla College of Arts, Science & Commerce, Kalyan",
  "Bombay College of Pharmacy, Santacruz",
  "Changu Kana Thakur Arts, Commerce and Science College, New Panvel",
  "Chetana’s Hazarimal Somani College of Commerce & Economics, Bandra",
  "Sir Sitaram and Lady Shantabai Patkar College, Goregaon",
  "College of Social Work Nirmala Niketan, Mumbai",
  "Kirti M. Doongursee College, Dadar",
  "Guru Nanak Khalsa College, Matunga",
  "Jai Hind College, Churchgate",
  "Kandivli Education Society’s B.K. Shroff College, Kandivali",
  "Vinayak Ganesh Vaze College (Kelkar College), Mulund",
  "K.J. Somaiya College of Arts and Commerce, Vidyavihar",
  "K.J. Somaiya College of Engineering, Vidyavihar",
  "K.J. Somaiya College of Science and Commerce, Vidyavihar",
  "K.P.B. Hinduja College of Commerce, Mumbai",
  "Pillai College of Engineering, New Panvel",
  "Nagindas Khandwala College, Malad",
  "Mulund College of Commerce, Mulund",
  "Sathaye College, Vile Parle",
  "Ramnarain Ruia College, Matunga",
  "Ramanand Arya D.A.V. College, Bhandup",
  "Karmaveer Bhaurao Patil College, Vashi",
  "R.A. Podar College of Commerce & Economics, Matunga",
  "Ramniranjan Jhunjhunwala College (R.J. College), Ghatkopar",
  "R.P. Gogate College of Arts and Science, Ratnagiri",
  "Sardar Patel College of Engineering, Andheri",
  "Sardar Patel Institute of Technology (SPIT), Andheri",
  "Mithibai College, Vile Parle",
  "Dwarkadas J. Sanghvi College of Engineering (D.J. Sanghvi), Vile Parle",
  "Narsee Monjee College of Commerce & Economics (NM College), Vile Parle",
  "SIES College of Arts, Science & Commerce, Sion",
  "Sophia College for Women, Mumbai",
  "St. Xavier’s College, Fort, Mumbai",
  "Thakur College of Science & Commerce, Kandivali",
  "Veermata Jijabai Technological Institute (VJTI), Matunga",
  "Vidyalankar Institute of Technology (VIT), Wadala",
  "Vivekanand Education Society’s Institute of Technology (VESIT), Chembur",
  "Wilson College, Girgaon",
  "Thakur College of Engineering & Technology (TCET), Kandivali",
  "Kohima Science College, Jotsoma",
  "Patkai Christian College, Dimapur",
  "St. Joseph’s College, Jakhama",
  "Govt. College, Phulbani",
  "College of Engineering & Technology (CET), Bhubaneswar",
  "DRIEMS Engineering College, Cuttack",
  "Gandhi Engineering College (GEC), Bhubaneswar",
  "Gandhi Institute of Engineering and Technology (GIET), Gunupur",
  "Gandhi Institute for Technological Advancement (GITA), Bhubaneswar",
  "Gandhi Institute for Technology (GIFT), Bhubaneswar",
  "Indira Gandhi Institute of Technology (IGIT), Sarang",
  "National Institute of Science & Technology (NIST), Berhampur",
  "Silicon Institute of Technology, Bhubaneswar",
  "Fakir Mohan College, Balasore",
  "Dharanidhar Autonomous College, Keonjhar",
  "Maharaja Purna Chandra Autonomous College, Baripada",
  "Buxi Jagabandhu Bidyadhar (BJB) Autonomous College, Bhubaneswar",
  "Kendrapara Autonomous College, Kendrapara",
  "Nayagarh Autonomous College, Nayagarh",
  "Prananath Autonomous College, Khordha",
  "Samanta Chandra Sekar College, Puri",
  "Udaya Nath College of Science and Technology, Adaspur",
  "Bharthidasan Government College for Women, Puducherry",
  "Indirani College of Nursing, Puducherry",
  "Kanchi Mamunivar Centre for P.G. Studies, Puducherry",
  "Manakula Vinayagar Institute of Technology, Puducherry",
  "Pondicherry Engineering College, Puducherry",
  "Sri Manakula Vinayagar Engineering College, Puducherry",
  "Tagore Government Arts and Science College, Puducherry",
  "Kanya Maha Vidyalaya, Jalandhar",
  "Khalsa College, Amritsar",
  "Amritsar College of Engineering & Technology, Amritsar",
  "Guru Nanak Dev Engineering College, Ludhiana",
  "ISF College of Pharmacy, Moga",
  "General Shivdev Singh Diwan Gurbachan Singh Khalsa College, Patiala",
  "Mata Gujri College, Fatehgarh Sahib",
  "Sri Guru Tegh Bahadur Khalsa College, Sri Anandpur Sahib",
  "Jodhpur Institute of Engineering & Technology, Jodhpur",
  "Lachoo Memorial College of Science and Technology, Jodhpur",
  "Sophia Girls College, Ajmer",
  "Arya College of Engineering and Information Technology, Jaipur",
  "International School of Information & Management, Jaipur",
  "Poornima College of Engineering, Jaipur",
  "Swami Keshvanand Institute of Technology (SKIT), Jaipur",
  "S.S. Jain Subodh P.G. College, Jaipur",
  "Parishkar College of Global Excellence, Jaipur",
  "Thassim Beevi Abdul Kader College for Women, Kilakarai",
  "AAA College of Engineering and Technology, Sivakasi",
  "Adhiyamaan College of Engineering, Hosur",
  "Adhiparasakthi Engineering College, Melmaruvathur",
  "Adithya Institute of Technology, Coimbatore",
  "Alagappa Chettiar Govt. College of Engineering and Technology, Karaikudi",
  "Bannari Amman Institute of Technology, Sathyamangalam",
  "Builders Engineering College, Kangeyam",
  "Chennai Institute of Technology, Kundrathur",
  "Coimbatore Institute of Technology (CIT), Coimbatore",
  "Dhanalakshmi Srinivasan Engineering College, Perambalur",
  "National Institute of Technology Rourkela",
  "Visvesvaraya National Institute of Technology Nagpur",
  "Netaji Subhas University of Technology",
  "Birla Institute of Technology",
  "International Institute of Information Technology Hyderabad",
  "BMS College of Engineering",
  "Institute of Chemical Technology",
  "Banaras Hindu University",
  "Thapar Institute of Engineering and Technology",
  "Shanmugha Arts Science Technology Research and Academy",
  "Indian Institute of Technology Hyderabad",
  "Nirma University",
  "Indraprastha Institute of Information Technology",
  "Lovely Professional University",
  "International Institute of Information Technology Bangalore",
  "Christ University",
  "Sardar Vallabhbhai National Institute of Technology Surat",
  "National Institute of Technology Durgapur",
  "PES University",
  "Indian Institute of Space Science and Technology",
  "Indian Institute of Technology Banaras Hindu University Varanasi",
  "Maharashtra Institute of Technology",
  "National Institute of Technology Delhi",
  "Veermata Jijabai Technological Institute",
  "Amrita School of Engineering",
  "National Institute of Technology Kurukshetra",
  "MIT College of Engineering",
  "College of Engineering Chennai",
  "Malaviya National Institute of Technology Jaipur",
  "Maulana Azad National Institute of Technology Bhopal",
  "Indian Institute of Information Technology Allahabad",
  "Indian Institute of Technology Guwahati",
  "Thiagarajar College of Engineering",
  "BITS Pilani- Hyderabad Campus",
  "JNTUH College of Engineering",
  "Maharaja Sayajirao University of Baroda",
  "Dhirubhai Ambani Institute of Information and Communication Technology",
  "Indian Institute of Technology Indian School of Mines Dhanbad",
  "Punjab Engineering College",
  "Harcourt Butler Technical University",
  "Indian Institute of Technology Indore",
  "Andhra University College of Engineering",
  "Sri Sivasubramaniya Nadar College of Engineering",
  "VIT University",
  "Bangalore Institute of Technology",
  "Vishwakarma Institute of Technology",
  "Indian Institute of Technology Gandhinagar",
  "Savitribai Phule Pune University",
  "Indian Institute of Technology Ropar",
  "Jamia Hamdard",
  "Panjab University",
  "Symbiosis International University",
  "Chandigarh University",
  "National Institute of Technology Silchar",
  "BMS Institute of Technology and Management",
  "Dayananda Sagar College of Engineering",
  "Jawaharlal Nehru University",
  "Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior",
  "JC Bose University of Science and Technology",
  "National Institute of Technology Raipur",
  "Chaitanya Bharathi Institute of Technology",
  "Institute of Engineering and Technology Lucknow",
  "Madras Institute of Technology",
  "University of Hyderabad",
  "Dr B R Ambedkar National Institute of Technology Jalandhar",
  "National Institute of Industrial Engineering",
  "Indian Institute of Technology Bhubaneswar",
  "Indian Institute of Technology Patna",
  "University of Calcutta",
  "Sharda University",
  "National Institute of Technology Jamshedpur",
  "Dr DY Patil University",
  "Heritage Institute of Technology",
  "Sinhgad College of Engineering",
  "University College of Engineering Hyderabad",
  "National Institute of Technology Hamirpur",
  "Government College of Engineering Aurangabad",
  "Bharati Vidyapeeth Deemed University College of Engineering",
  "Maulana Abul Kalam Azad University of Technology",
];

