export const GLOBAL_JOB_ROLES: string[] = [
  "Software Engineer",
  "Software Developer",
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "Flutter Developer",
  "React Native Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Cloud Consultant",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "Deep Learning Engineer",
  "QA Engineer",
  "Test Engineer",
  "Automation Engineer",
  "Manual Tester",
  "Performance Test Engineer",
  "Security Engineer",
  "Network Engineer",
  "Systems Administrator",
  "Database Administrator",
  "Database Developer",
  "Product Manager",
  "Project Manager",
  "Program Manager",
  "Scrum Master",
  "Agile Coach",
  "Business Analyst",
  "UX Designer",
  "UI Designer",
  "UX Researcher",
  "Product Designer",
  "Technical Writer",
  "Solutions Architect",
  "Enterprise Architect",
  "Cloud Architect",
  "Software Architect",
  "Infrastructure Engineer",
  "Platform Engineer",
  "Release Engineer",
  "Build Engineer",
  "Support Engineer",
  "Technical Support Specialist",
  "Customer Success Manager",
  "Sales Engineer",
  "Pre-Sales Engineer",
  "IT Manager",
  "IT Support Specialist",
  "Help Desk Technician",
  "Network Administrator",
  "Systems Engineer",
  "Embedded Systems Engineer",
  "Firmware Engineer",
  "Game Developer",
  "Game Designer",
  "Game Programmer",
  "Blockchain Developer",
  "Web Developer",
  "WordPress Developer",
  "Shopify Developer",
  "Salesforce Developer",
  "SAP Consultant",
  "ERP Consultant",
  "Data Warehouse Engineer",
  "BI Developer",
  "Business Intelligence Analyst",
  "Research Scientist",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Robotics Engineer",
  "Hardware Engineer",
  "Chip Design Engineer",
  "VLSI Engineer",
  "IT Auditor",
  "Compliance Analyst",
  "Cybersecurity Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "Security Analyst",
  "SOC Analyst",
  "Incident Response Analyst",
  "Cryptographer",
  "Technical Program Manager",
  "Engineering Manager",
  "Growth Engineer",
  "Marketing Technologist",
  "SEO Specialist",
  "Digital Marketing Manager",
  "Content Strategist",
  "Community Manager",
  "Developer Advocate",
  "Developer Relations Engineer",
  "Technical Recruiter",
  "HR Technology Specialist",
  "Localization Engineer",
  "Internationalization Engineer",
  "Performance Engineer",
  "Reliability Engineer",
  "Chaos Engineer",
  "Observability Engineer",
  "API Developer",
  "Integration Engineer",
  "ETL Developer",
  "Data Pipeline Engineer",
  "MLOps Engineer",
  "AIOps Engineer",
  "Prompt Engineer",
  "Conversational AI Designer",
  "Voice UX Designer",
  "AR Developer",
  "VR Developer",
  "XR Engineer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Graphics Programmer",
  "Rendering Engineer",
  "Compiler Engineer",
  "Kernel Engineer",
  "OS Developer",
  "Distributed Systems Engineer",
  "Big Data Engineer",
  "Hadoop Developer",
  "Spark Developer",
  "Kafka Engineer",
  "Search Engineer",
  "Recommendation Systems Engineer",
  "Fraud Detection Engineer",
  "Payments Engineer",
  "Fintech Developer",
  "Healthtech Developer",
  "Edtech Developer",
  "IoT Engineer",
  "Automotive Software Engineer",
  "Avionics Software Engineer",
  "Telecom Engineer",
  "Network Security Engineer",
  "Cloud Security Engineer",
  "Application Security Engineer",
  "Identity and Access Management Engineer",
  "DevSecOps Engineer",
  "Configuration Manager",
  "Release Manager",
  "Change Manager",
  "ITIL Consultant",
  "ServiceNow Developer",
  "RPA Developer",
  "Automation Architect",
  "Low-Code Developer",
  "No-Code Developer",
  "CRM Administrator",
  "CRM Developer",
  "Business Systems Analyst",
  "Functional Consultant",
  "Technical Consultant",
  "IT Consultant",
  "Management Consultant",
  "Strategy Consultant",
  "Innovation Manager",
  "R&D Engineer",
  "Applied Scientist",
  "Data Governance Analyst",
  "Master Data Management Specialist",
  "Data Quality Analyst",
  "Data Steward",
  "Storage Engineer",
  "Backup Engineer",
  "Virtualization Engineer",
  "VMware Administrator",
  "Citrix Administrator",
  "Linux Administrator",
  "Windows Administrator",
  "Unix Administrator",
  "Mainframe Developer",
  "COBOL Developer",
  "Legacy Systems Engineer",
  "Migration Engineer",
  "Cloud Migration Specialist",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Kubernetes Engineer",
  "Docker Specialist",
  "Terraform Engineer",
  "Ansible Engineer",
  "Puppet Engineer",
  "Chef Automation Engineer",
  "CI/CD Engineer",
  "Jenkins Administrator",
  "GitOps Engineer",
  "Version Control Administrator",
  "Source Code Manager",
  "Application Developer",
  "Systems Analyst",
  "Solutions Consultant",
  "Implementation Engineer",
  "Onboarding Specialist",
  "Technical Account Manager",
  "Customer Support Engineer",
  "Field Engineer",
  "Deployment Engineer",
  "Escalation Engineer",
  "Quality Assurance Analyst",
  "Quality Assurance Lead",
  "Test Automation Architect",
  "Load Test Engineer",
  "Security Compliance Officer",
  "Risk Analyst",
  "Governance Risk and Compliance Analyst",
  "Privacy Engineer",
  "Data Privacy Officer",
  "Cloud FinOps Engineer",
  "IT Asset Manager",
  "IT Procurement Specialist",
  "Vendor Manager",
  "Technical Program Coordinator",
  "Delivery Manager",
  "Portfolio Manager",
  "Chief of Staff (Engineering)",
  "Innovation Lab Engineer",
  "Research Engineer",
  "Simulation Engineer",
  "Numerical Analyst",
  "Quantitative Developer",
  "Algorithmic Trading Developer",
  "High Frequency Trading Engineer",
  "Bioinformatics Engineer",
  "Geospatial Developer",
  "GIS Analyst",
  "CAD Software Engineer",
  "Digital Twin Engineer",
  "Simulation Software Developer",
  "Firmware Test Engineer",
  "Hardware Verification Engineer",
  "FPGA Engineer",
  "ASIC Design Engineer",
  "Signal Processing Engineer",
  "Telecommunications Software Engineer",
  "5G Network Engineer",
  "Satellite Systems Engineer",
  "Aerospace Software Engineer",
  "Defense Systems Engineer",
  "Cybersecurity Architect",
  "Threat Intelligence Analyst",
  "Malware Analyst",
  "Digital Forensics Analyst",
  "Vulnerability Analyst",
  "Red Team Engineer",
  "Blue Team Analyst",
  "Purple Team Engineer",
  "Security Operations Manager",
  "Application Support Analyst",
  "Production Support Engineer",
  "Middleware Administrator",
  "API Gateway Engineer",
  "Message Queue Engineer",
  "Microservices Developer",
  "Serverless Developer",
  "Event-Driven Architecture Engineer",
  "GraphQL Developer",
  "REST API Engineer",
  "Backend Systems Engineer",
  "Frontend Systems Engineer",
  "Accessibility Engineer",
  "Design Systems Engineer",
  "Motion Designer",
  "Interaction Designer",
  "Visual Designer",
  "Information Architect",
  "Content Designer",
  "Technical Illustrator",
  "Instructional Designer",
  "E-Learning Developer",
  "Curriculum Developer",
  "Training Specialist",
  "Knowledge Management Analyst",
  "Documentation Specialist",
  "API Documentation Writer",
  "Developer Experience Engineer",
  "Internal Tools Engineer",
  "Productivity Engineer",
  "Workflow Automation Engineer",
  "Chatbot Developer",
  "Virtual Assistant Developer",
  "Speech Recognition Engineer",
  "Text-to-Speech Engineer",
  "Recommendation Engine Developer",
  "Personalization Engineer",
  "Growth Product Manager",
  "Technical Product Manager",
  "Platform Product Manager",
  "API Product Manager",
  "Data Product Manager",
  "Mobile Product Manager",
  "Design Product Manager",
  "Associate Product Manager",
  "Group Product Manager",
  "Product Owner",
  "Release Train Engineer",
  "Kanban Coach",
  "Lean Coach",
  "Delivery Lead",
  "Iteration Manager",
  "Requirements Analyst",
  "Systems Requirements Engineer",
  "Solution Designer",
  "Technical Business Consultant",
  "Digital Transformation Consultant",
  "Innovation Strategist",
  "Emerging Technology Analyst",
  "Blockchain Architect",
  "Smart Contract Developer",
  "Web3 Developer",
  "Cryptocurrency Developer",
  "DeFi Engineer",
  "NFT Platform Developer",
  "Metaverse Developer",
  "Quantum Computing Engineer",
  "Quantum Software Developer",
  "Edge Computing Engineer",
  "Fog Computing Engineer",
  "Network Operations Engineer",
  "Data Center Technician",
  "Colocation Engineer",
  "Capacity Planning Engineer",
  "Cost Optimization Engineer",
  "Cloud Cost Analyst",
  "Sustainability Software Engineer",
  "Green IT Consultant",
  "IT Governance Analyst",
  "Enterprise Data Architect",
  "Master Data Architect",
  "Information Security Manager",
  "Chief Information Officer",
  "Chief Technology Officer",
  "Chief Product Officer",
  "Chief Data Officer",
  "Chief Information Security Officer",
  "Chief Digital Officer",
  "Vice President of Engineering",
  "Vice President of Product",
  "Vice President of Data",
  "Vice President of Technology",
  "Director of Engineering",
  "Director of Product",
  "Director of Data Science",
  "Director of QA",
  "Director of DevOps",
  "Director of Security",
  "Director of Infrastructure",
  "Head of Product",
  "Head of Design",
  "Head of Engineering",
  "Head of Security",
  "Head of Infrastructure",
  "Head of Data",
  "Head of Platform",
  "Head of Mobile",
  "Junior Software Engineer",
  "Junior Software Developer",
  "Junior Backend Developer",
  "Junior Frontend Developer",
  "Junior Full Stack Developer",
  "Junior Mobile Developer",
  "Junior iOS Developer",
  "Junior Android Developer",
  "Junior Flutter Developer",
  "Junior React Native Developer",
  "Junior DevOps Engineer",
  "Junior Site Reliability Engineer",
  "Junior Cloud Engineer",
  "Junior Cloud Consultant",
  "Junior Data Engineer",
  "Junior Data Scientist",
  "Junior Data Analyst",
  "Junior Machine Learning Engineer",
  "Junior AI Engineer",
  "Junior Deep Learning Engineer",
  "Junior QA Engineer",
  "Junior Test Engineer",
  "Junior Automation Engineer",
  "Junior Manual Tester",
  "Junior Performance Test Engineer",
  "Junior Security Engineer",
  "Junior Network Engineer",
  "Junior Systems Administrator",
  "Junior Database Administrator",
  "Junior Database Developer",
  "Junior Product Manager",
  "Junior Project Manager",
  "Junior Program Manager",
  "Junior Scrum Master",
  "Junior Agile Coach",
  "Junior Business Analyst",
  "Junior UX Designer",
  "Junior UI Designer",
  "Junior UX Researcher",
  "Junior Product Designer",
  "Junior Technical Writer",
  "Junior Solutions Architect",
  "Junior Enterprise Architect",
  "Junior Cloud Architect",
  "Junior Software Architect",
  "Junior Infrastructure Engineer",
  "Junior Platform Engineer",
  "Junior Release Engineer",
  "Junior Build Engineer",
  "Junior Support Engineer",
  "Junior Technical Support Specialist",
  "Junior Customer Success Manager",
  "Junior Sales Engineer",
  "Junior Pre-Sales Engineer",
  "Junior IT Manager",
  "Junior IT Support Specialist",
  "Junior Help Desk Technician",
  "Junior Network Administrator",
  "Junior Systems Engineer",
  "Junior Embedded Systems Engineer",
  "Junior Firmware Engineer",
  "Junior Game Developer",
  "Junior Game Designer",
  "Junior Game Programmer",
  "Junior Blockchain Developer",
  "Junior Web Developer",
  "Junior WordPress Developer",
  "Junior Shopify Developer",
  "Junior Salesforce Developer",
  "Junior SAP Consultant",
  "Junior ERP Consultant",
  "Junior Data Warehouse Engineer",
  "Junior BI Developer",
  "Junior Business Intelligence Analyst",
  "Junior Research Scientist",
  "Junior Computer Vision Engineer",
  "Junior NLP Engineer",
  "Junior Robotics Engineer",
  "Junior Hardware Engineer",
  "Junior Chip Design Engineer",
  "Junior VLSI Engineer",
  "Junior IT Auditor",
  "Junior Compliance Analyst",
  "Junior Cybersecurity Analyst",
  "Junior Penetration Tester",
  "Junior Ethical Hacker",
  "Junior Security Analyst",
  "Junior SOC Analyst",
  "Junior Incident Response Analyst",
  "Junior Cryptographer",
  "Junior Technical Program Manager",
  "Junior Engineering Manager",
  "Junior Growth Engineer",
  "Junior Marketing Technologist",
  "Junior SEO Specialist",
  "Junior Digital Marketing Manager",
  "Junior Content Strategist",
  "Junior Community Manager",
  "Junior Developer Advocate",
  "Junior Developer Relations Engineer",
  "Junior Technical Recruiter",
  "Junior HR Technology Specialist",
  "Junior Localization Engineer",
  "Junior Internationalization Engineer",
  "Junior Performance Engineer",
  "Junior Reliability Engineer",
  "Junior Chaos Engineer",
  "Junior Observability Engineer",
  "Junior API Developer",
  "Junior Integration Engineer",
  "Junior ETL Developer",
  "Junior Data Pipeline Engineer",
  "Junior MLOps Engineer",
  "Junior AIOps Engineer",
  "Junior Prompt Engineer",
  "Junior Conversational AI Designer",
  "Junior Voice UX Designer",
  "Junior AR Developer",
  "Junior VR Developer",
  "Junior XR Engineer",
  "Junior Unity Developer",
  "Junior Unreal Engine Developer",
  "Junior Graphics Programmer",
  "Junior Rendering Engineer",
  "Junior Compiler Engineer",
  "Junior Kernel Engineer",
  "Junior OS Developer",
  "Junior Distributed Systems Engineer",
  "Junior Big Data Engineer",
  "Junior Hadoop Developer",
  "Junior Spark Developer",
  "Junior Kafka Engineer",
  "Junior Search Engineer",
  "Junior Recommendation Systems Engineer",
  "Junior Fraud Detection Engineer",
  "Junior Payments Engineer",
  "Junior Fintech Developer",
  "Junior Healthtech Developer",
  "Junior Edtech Developer",
  "Junior IoT Engineer",
  "Junior Automotive Software Engineer",
  "Junior Avionics Software Engineer",
  "Junior Telecom Engineer",
  "Junior Network Security Engineer",
  "Junior Cloud Security Engineer",
  "Junior Application Security Engineer",
  "Junior Identity and Access Management Engineer",
  "Junior DevSecOps Engineer",
  "Junior Configuration Manager",
  "Junior Release Manager",
  "Junior Change Manager",
  "Junior ITIL Consultant",
  "Junior ServiceNow Developer",
  "Junior RPA Developer",
  "Junior Automation Architect",
  "Junior Low-Code Developer",
  "Junior No-Code Developer",
  "Junior CRM Administrator",
  "Junior CRM Developer",
  "Junior Business Systems Analyst",
  "Junior Functional Consultant",
  "Junior Technical Consultant",
  "Junior IT Consultant",
  "Junior Management Consultant",
  "Junior Strategy Consultant",
  "Junior Innovation Manager",
  "Junior R&D Engineer",
  "Junior Applied Scientist",
  "Junior Data Governance Analyst",
  "Junior Master Data Management Specialist",
  "Junior Data Quality Analyst",
  "Junior Data Steward",
  "Junior Storage Engineer",
  "Junior Backup Engineer",
  "Junior Virtualization Engineer",
  "Junior VMware Administrator",
  "Junior Citrix Administrator",
  "Junior Linux Administrator",
  "Junior Windows Administrator",
  "Junior Unix Administrator",
  "Junior Mainframe Developer",
  "Junior COBOL Developer",
  "Junior Legacy Systems Engineer",
  "Junior Migration Engineer",
  "Junior Cloud Migration Specialist",
  "Junior AWS Engineer",
  "Junior Azure Engineer",
  "Junior GCP Engineer",
  "Junior Kubernetes Engineer",
  "Junior Docker Specialist",
  "Junior Terraform Engineer",
  "Junior Ansible Engineer",
  "Junior Puppet Engineer",
  "Junior Chef Automation Engineer",
  "Junior CI/CD Engineer",
  "Junior Jenkins Administrator",
  "Junior GitOps Engineer",
  "Junior Version Control Administrator",
  "Junior Source Code Manager",
  "Junior Application Developer",
  "Junior Systems Analyst",
  "Junior Solutions Consultant",
  "Junior Implementation Engineer",
  "Junior Onboarding Specialist",
  "Junior Technical Account Manager",
  "Junior Customer Support Engineer",
  "Junior Field Engineer",
  "Junior Deployment Engineer",
  "Junior Escalation Engineer",
  "Junior Quality Assurance Analyst",
  "Junior Quality Assurance Lead",
  "Junior Test Automation Architect",
  "Junior Load Test Engineer",
  "Junior Security Compliance Officer",
  "Junior Risk Analyst",
  "Junior Governance Risk and Compliance Analyst",
  "Junior Privacy Engineer",
  "Junior Data Privacy Officer",
  "Junior Cloud FinOps Engineer",
  "Junior IT Asset Manager",
  "Junior IT Procurement Specialist",
  "Junior Vendor Manager",
  "Junior Technical Program Coordinator",
  "Junior Delivery Manager",
  "Junior Portfolio Manager",
  "Junior Chief of Staff (Engineering)",
  "Junior Innovation Lab Engineer",
  "Junior Research Engineer",
  "Junior Simulation Engineer",
  "Junior Numerical Analyst",
  "Junior Quantitative Developer",
  "Junior Algorithmic Trading Developer",
  "Junior High Frequency Trading Engineer",
  "Junior Bioinformatics Engineer",
  "Junior Geospatial Developer",
  "Junior GIS Analyst",
  "Junior CAD Software Engineer",
  "Junior Digital Twin Engineer",
  "Junior Simulation Software Developer",
  "Junior Firmware Test Engineer",
  "Junior Hardware Verification Engineer",
  "Junior FPGA Engineer",
  "Junior ASIC Design Engineer",
  "Junior Signal Processing Engineer",
  "Junior Telecommunications Software Engineer",
  "Junior 5G Network Engineer",
  "Junior Satellite Systems Engineer",
  "Junior Aerospace Software Engineer",
  "Junior Defense Systems Engineer",
  "Junior Cybersecurity Architect",
  "Junior Threat Intelligence Analyst",
  "Junior Malware Analyst",
  "Junior Digital Forensics Analyst",
  "Junior Vulnerability Analyst",
  "Junior Red Team Engineer",
  "Junior Blue Team Analyst",
  "Junior Purple Team Engineer",
  "Junior Security Operations Manager",
  "Junior Application Support Analyst",
  "Junior Production Support Engineer",
  "Junior Middleware Administrator",
  "Junior API Gateway Engineer",
  "Junior Message Queue Engineer",
  "Junior Microservices Developer",
  "Junior Serverless Developer",
  "Junior Event-Driven Architecture Engineer",
  "Junior GraphQL Developer",
  "Junior REST API Engineer",
  "Junior Backend Systems Engineer",
  "Junior Frontend Systems Engineer",
  "Junior Accessibility Engineer",
  "Junior Design Systems Engineer",
  "Junior Motion Designer",
  "Junior Interaction Designer",
  "Junior Visual Designer",
  "Junior Information Architect",
  "Junior Content Designer",
  "Junior Technical Illustrator",
  "Junior Instructional Designer",
  "Junior E-Learning Developer",
  "Junior Curriculum Developer",
  "Junior Training Specialist",
  "Junior Knowledge Management Analyst",
  "Junior Documentation Specialist",
  "Junior API Documentation Writer",
  "Junior Developer Experience Engineer",
  "Junior Internal Tools Engineer",
  "Junior Productivity Engineer",
  "Junior Workflow Automation Engineer",
  "Junior Chatbot Developer",
  "Junior Virtual Assistant Developer",
  "Junior Speech Recognition Engineer",
  "Junior Text-to-Speech Engineer",
  "Junior Recommendation Engine Developer",
  "Junior Personalization Engineer",
  "Junior Growth Product Manager",
  "Junior Technical Product Manager",
  "Junior Platform Product Manager",
  "Junior API Product Manager",
  "Junior Data Product Manager",
  "Junior Mobile Product Manager",
  "Junior Design Product Manager",
  "Junior Associate Product Manager",
  "Junior Group Product Manager",
  "Junior Product Owner",
  "Junior Release Train Engineer",
  "Junior Kanban Coach",
  "Junior Lean Coach",
  "Junior Delivery Lead",
  "Junior Iteration Manager",
  "Junior Requirements Analyst",
  "Junior Systems Requirements Engineer",
  "Junior Solution Designer",
  "Junior Technical Business Consultant",
  "Junior Digital Transformation Consultant",
  "Junior Innovation Strategist",
  "Junior Emerging Technology Analyst",
  "Junior Blockchain Architect",
  "Junior Smart Contract Developer",
  "Junior Web3 Developer",
  "Junior Cryptocurrency Developer",
  "Junior DeFi Engineer",
  "Junior NFT Platform Developer",
  "Junior Metaverse Developer",
  "Junior Quantum Computing Engineer",
  "Junior Quantum Software Developer",
  "Junior Edge Computing Engineer",
  "Junior Fog Computing Engineer",
  "Junior Network Operations Engineer",
  "Junior Data Center Technician",
  "Junior Colocation Engineer",
  "Junior Capacity Planning Engineer",
  "Junior Cost Optimization Engineer",
  "Junior Cloud Cost Analyst",
  "Junior Sustainability Software Engineer",
  "Junior Green IT Consultant",
  "Junior IT Governance Analyst",
  "Junior Enterprise Data Architect",
  "Junior Master Data Architect",
  "Junior Information Security Manager",
  "Junior Chief Information Officer",
  "Junior Chief Technology Officer",
  "Junior Chief Product Officer",
  "Junior Chief Data Officer",
  "Junior Chief Information Security Officer",
  "Junior Chief Digital Officer",
  "Junior Vice President of Engineering",
  "Junior Vice President of Product",
  "Junior Vice President of Data",
  "Junior Vice President of Technology",
  "Junior Director of Engineering",
  "Junior Director of Product",
  "Junior Director of Data Science",
  "Junior Director of QA",
  "Junior Director of DevOps",
  "Junior Director of Security",
  "Junior Director of Infrastructure",
  "Junior Head of Product",
  "Junior Head of Design",
  "Junior Head of Engineering",
  "Junior Head of Security",
  "Junior Head of Infrastructure",
  "Junior Head of Data",
  "Junior Head of Platform",
  "Junior Head of Mobile",
  "Senior Software Engineer",
  "Senior Software Developer",
  "Senior Backend Developer",
  "Senior Frontend Developer",
  "Senior Full Stack Developer",
  "Senior Mobile Developer",
  "Senior iOS Developer",
  "Senior Android Developer",
  "Senior Flutter Developer",
  "Senior React Native Developer",
  "Senior DevOps Engineer",
  "Senior Site Reliability Engineer",
  "Senior Cloud Engineer",
  "Senior Cloud Consultant",
  "Senior Data Engineer",
  "Senior Data Scientist",
  "Senior Data Analyst",
  "Senior Machine Learning Engineer",
  "Senior AI Engineer",
  "Senior Deep Learning Engineer",
  "Senior QA Engineer",
  "Senior Test Engineer",
  "Senior Automation Engineer",
  "Senior Manual Tester",
  "Senior Performance Test Engineer",
  "Senior Security Engineer",
  "Senior Network Engineer",
  "Senior Systems Administrator",
  "Senior Database Administrator",
  "Senior Database Developer",
  "Senior Product Manager",
  "Senior Project Manager",
  "Senior Program Manager",
  "Senior Scrum Master",
  "Senior Agile Coach",
  "Senior Business Analyst",
  "Senior UX Designer",
  "Senior UI Designer",
  "Senior UX Researcher",
  "Senior Product Designer",
  "Senior Technical Writer",
  "Senior Solutions Architect",
  "Senior Enterprise Architect",
  "Senior Cloud Architect",
  "Senior Software Architect",
  "Senior Infrastructure Engineer",
  "Senior Platform Engineer",
  "Senior Release Engineer",
  "Senior Build Engineer",
  "Senior Support Engineer",
  "Senior Technical Support Specialist",
  "Senior Customer Success Manager",
  "Senior Sales Engineer",
  "Senior Pre-Sales Engineer",
  "Senior IT Manager",
  "Senior IT Support Specialist",
  "Senior Help Desk Technician",
  "Senior Network Administrator",
  "Senior Systems Engineer",
  "Senior Embedded Systems Engineer",
  "Senior Firmware Engineer",
  "Senior Game Developer",
  "Senior Game Designer",
  "Senior Game Programmer",
  "Senior Blockchain Developer",
  "Senior Web Developer",
  "Senior WordPress Developer",
  "Senior Shopify Developer",
  "Senior Salesforce Developer",
  "Senior SAP Consultant",
  "Senior ERP Consultant",
  "Senior Data Warehouse Engineer",
  "Senior BI Developer",
  "Senior Business Intelligence Analyst",
  "Senior Research Scientist",
  "Senior Computer Vision Engineer",
  "Senior NLP Engineer",
  "Senior Robotics Engineer",
  "Senior Hardware Engineer",
  "Senior Chip Design Engineer",
  "Senior VLSI Engineer",
  "Senior IT Auditor",
  "Senior Compliance Analyst",
  "Senior Cybersecurity Analyst",
  "Senior Penetration Tester",
  "Senior Ethical Hacker",
  "Senior Security Analyst",
  "Senior SOC Analyst",
  "Senior Incident Response Analyst",
  "Senior Cryptographer",
  "Senior Technical Program Manager",
  "Senior Engineering Manager",
  "Senior Growth Engineer",
  "Senior Marketing Technologist",
  "Senior SEO Specialist",
  "Senior Digital Marketing Manager",
  "Senior Content Strategist",
  "Senior Community Manager",
  "Senior Developer Advocate",
  "Senior Developer Relations Engineer",
  "Senior Technical Recruiter",
  "Senior HR Technology Specialist",
  "Senior Localization Engineer",
  "Senior Internationalization Engineer",
  "Senior Performance Engineer",
  "Senior Reliability Engineer",
  "Senior Chaos Engineer",
  "Senior Observability Engineer",
  "Senior API Developer",
  "Senior Integration Engineer",
  "Senior ETL Developer",
  "Senior Data Pipeline Engineer",
  "Senior MLOps Engineer",
  "Senior AIOps Engineer",
  "Senior Prompt Engineer",
  "Senior Conversational AI Designer",
  "Senior Voice UX Designer",
  "Senior AR Developer",
  "Senior VR Developer",
  "Senior XR Engineer",
  "Senior Unity Developer",
  "Senior Unreal Engine Developer",
  "Senior Graphics Programmer",
  "Senior Rendering Engineer",
  "Senior Compiler Engineer",
  "Senior Kernel Engineer",
  "Senior OS Developer",
  "Senior Distributed Systems Engineer",
  "Senior Big Data Engineer",
  "Senior Hadoop Developer",
  "Senior Spark Developer",
  "Senior Kafka Engineer",
  "Senior Search Engineer",
  "Senior Recommendation Systems Engineer",
  "Senior Fraud Detection Engineer",
  "Senior Payments Engineer",
  "Senior Fintech Developer",
  "Senior Healthtech Developer",
  "Senior Edtech Developer",
  "Senior IoT Engineer",
  "Senior Automotive Software Engineer",
  "Senior Avionics Software Engineer",
  "Senior Telecom Engineer",
  "Senior Network Security Engineer",
  "Senior Cloud Security Engineer",
  "Senior Application Security Engineer",
  "Senior Identity and Access Management Engineer",
  "Senior DevSecOps Engineer",
  "Senior Configuration Manager",
  "Senior Release Manager",
  "Senior Change Manager",
  "Senior ITIL Consultant",
  "Senior ServiceNow Developer",
  "Senior RPA Developer",
  "Senior Automation Architect",
  "Senior Low-Code Developer",
  "Senior No-Code Developer",
  "Senior CRM Administrator",
  "Senior CRM Developer",
  "Senior Business Systems Analyst",
  "Senior Functional Consultant",
  "Senior Technical Consultant",
  "Senior IT Consultant",
  "Senior Management Consultant",
  "Senior Strategy Consultant",
  "Senior Innovation Manager",
  "Senior R&D Engineer",
  "Senior Applied Scientist",
  "Senior Data Governance Analyst",
  "Senior Master Data Management Specialist",
  "Senior Data Quality Analyst",
  "Senior Data Steward",
  "Senior Storage Engineer",
  "Senior Backup Engineer",
  "Senior Virtualization Engineer",
  "Senior VMware Administrator",
  "Senior Citrix Administrator",
  "Senior Linux Administrator",
  "Senior Windows Administrator",
  "Senior Unix Administrator",
  "Senior Mainframe Developer",
  "Senior COBOL Developer",
  "Senior Legacy Systems Engineer",
  "Senior Migration Engineer",
  "Senior Cloud Migration Specialist",
  "Senior AWS Engineer",
  "Senior Azure Engineer",
  "Senior GCP Engineer",
  "Senior Kubernetes Engineer",
  "Senior Docker Specialist",
  "Senior Terraform Engineer",
  "Senior Ansible Engineer",
  "Senior Puppet Engineer",
  "Senior Chef Automation Engineer",
  "Senior CI/CD Engineer",
  "Senior Jenkins Administrator",
  "Senior GitOps Engineer",
  "Senior Version Control Administrator",
  "Senior Source Code Manager",
  "Senior Application Developer",
  "Senior Systems Analyst",
  "Senior Solutions Consultant",
  "Senior Implementation Engineer",
  "Senior Onboarding Specialist",
  "Senior Technical Account Manager",
  "Senior Customer Support Engineer",
  "Senior Field Engineer",
  "Senior Deployment Engineer",
  "Senior Escalation Engineer",
  "Senior Quality Assurance Analyst",
  "Senior Quality Assurance Lead",
  "Senior Test Automation Architect",
  "Senior Load Test Engineer",
  "Senior Security Compliance Officer",
  "Senior Risk Analyst",
  "Senior Governance Risk and Compliance Analyst",
  "Senior Privacy Engineer",
  "Senior Data Privacy Officer",
  "Senior Cloud FinOps Engineer",
  "Senior IT Asset Manager",
  "Senior IT Procurement Specialist",
  "Senior Vendor Manager",
  "Senior Technical Program Coordinator",
  "Senior Delivery Manager",
  "Senior Portfolio Manager",
  "Senior Chief of Staff (Engineering)",
  "Senior Innovation Lab Engineer",
  "Senior Research Engineer",
  "Senior Simulation Engineer",
  "Senior Numerical Analyst",
  "Senior Quantitative Developer",
  "Senior Algorithmic Trading Developer",
  "Senior High Frequency Trading Engineer",
  "Senior Bioinformatics Engineer",
  "Senior Geospatial Developer",
  "Senior GIS Analyst",
  "Senior CAD Software Engineer",
  "Senior Digital Twin Engineer",
  "Senior Simulation Software Developer",
  "Senior Firmware Test Engineer",
  "Senior Hardware Verification Engineer",
  "Senior FPGA Engineer",
  "Senior ASIC Design Engineer",
  "Senior Signal Processing Engineer",
  "Senior Telecommunications Software Engineer",
  "Senior 5G Network Engineer",
  "Senior Satellite Systems Engineer",
  "Senior Aerospace Software Engineer",
  "Senior Defense Systems Engineer",
  "Senior Cybersecurity Architect",
  "Senior Threat Intelligence Analyst",
  "Senior Malware Analyst",
  "Senior Digital Forensics Analyst",
  "Senior Vulnerability Analyst",
  "Senior Red Team Engineer",
  "Senior Blue Team Analyst",
  "Senior Purple Team Engineer",
  "Senior Security Operations Manager",
  "Senior Application Support Analyst",
  "Senior Production Support Engineer",
  "Senior Middleware Administrator",
  "Senior API Gateway Engineer",
  "Senior Message Queue Engineer",
  "Senior Microservices Developer",
  "Senior Serverless Developer",
  "Senior Event-Driven Architecture Engineer",
  "Senior GraphQL Developer",
  "Senior REST API Engineer",
  "Senior Backend Systems Engineer",
  "Senior Frontend Systems Engineer"
];
